#!/usr/bin/env python3
"""Generate a fine-grained, S21+-priority fleet-state matrix for the PV-surplus
controller.

The fleet's S21+ is the most efficient miner but has a high power-target minimum
(2457 W), so it cannot run on small surplus. This matrix therefore:

  1. runs the low-minimum S19j Pro+ alone to hold tiny surplus,
  2. brings the S21+ online and ramps it to full FIRST (max hashrate per watt),
  3. adds the S19j Pro, then ramps the two S19j units up to their defaults.

Ramps use ~`STEP_W` (200 W) increments so the snap-to-surplus controller can
track the surplus closely. State totals are strictly monotonic. The unavoidable
jumps (a miner's minimum when it joins) are a hardware constraint, not a bug.

Run: python scripts/gen_s21_priority_matrix.py > pv_fleet_states.yaml
"""
from __future__ import annotations

STEP_W = 200

# (id, min_power_w, default_power_w) — edit to match your fleet.
PRO_PLUS = ("s19j_pro_plus", 817, 3300)
PRO = ("s19j_pro", 944, 3068)
S21 = ("s21_plus", 2457, 3878)


def ramp(lo: int, hi: int, step: int) -> list[int]:
    """Inclusive levels lo..hi in ~step increments (lo first, hi last)."""
    if hi <= lo:
        return [lo]
    n = max(1, round((hi - lo) / step))
    return [round(lo + (hi - lo) * k / n) for k in range(n + 1)]


def build() -> list[dict]:
    """Return an ordered list of states; each is {id: watts|None(=sleep)}."""
    pp, pp_min, pp_def = PRO_PLUS
    pr, pr_min, pr_def = PRO
    s, s_min, s_def = S21
    states: list[dict] = []

    def add(**watts):
        states.append({pp: watts.get(pp), pr: watts.get(pr), s: watts.get(s)})

    add()                                   # 0: all off
    add(**{pp: pp_min})                     # 1: Pro+ holds tiny surplus
    for lvl in ramp(s_min, s_def, STEP_W):  # S21+ joins and ramps to full first
        add(**{pp: pp_min, s: lvl})
    base = {pp: pp_min, s: s_def}
    add(**{**base, pr: pr_min})             # Pro joins at minimum
    for lvl in ramp(pp_min, pp_def, STEP_W)[1:]:   # ramp Pro+ to default (S21 full, Pro min)
        add(**{pp: lvl, s: s_def, pr: pr_min})
    for lvl in ramp(pr_min, pr_def, STEP_W)[1:]:   # ramp Pro to default (S21 + Pro+ full)
        add(**{pp: pp_def, s: s_def, pr: lvl})

    # de-dup consecutive identical states (rounding can repeat the endpoint)
    deduped = [states[0]]
    for st in states[1:]:
        if st != deduped[-1]:
            deduped.append(st)
    return deduped


def total(st: dict) -> int:
    return sum(v for v in st.values() if v)


def to_yaml(states: list[dict]) -> str:
    ids = [PRO_PLUS[0], PRO[0], S21[0]]
    width = max(len(i) for i in ids)
    out = [
        "# Fine-grained, S21+-priority fleet matrix (generated by",
        "# scripts/gen_s21_priority_matrix.py). ~200 W steps; totals monotonic.",
        "# S21+ is ramped to full first (most hashrate/W), then the S19j units.",
        "states:",
    ]
    for sid, st in enumerate(states):
        out.append(f"  {sid}:   # total {total(st)} W")
        for mid in ids:
            w = st.get(mid)
            pad = " " * (width - len(mid))
            if w is None:
                out.append(f"    {mid}:{pad} {{ action: sleep }}")
            else:
                out.append(f"    {mid}:{pad} {{ action: active, power_w: {w} }}")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    import sys
    sts = build()
    totals = [total(s) for s in sts]
    assert totals == sorted(totals), f"totals not monotonic: {totals}"
    sys.stderr.write(f"{len(sts)} states (0..{len(sts)-1}); totals={totals}\n")
    sys.stdout.write(to_yaml(sts))
